linker.cpp: fix for missing RelocationInfo.h
Facing build failure with below error:

git/core/compiler_interface/linker.cpp:14:10: fatal error: RelocationInfo.h: No such file or directory
|    14 | #include "RelocationInfo.h"
|       |          ^~~~~~~~~~~~~~~~~~
| compilation terminated.

Signed-off-by: Naveen Saini <naveen.kumar.saini@intel.com>